name = "tiny"
main = "src/index.js"
compatibility_date = "2025-03-01"
workers_dev = true
preview_urls = true

[[routes]]
pattern = "tinyactive.net/*"
zone_name = "tinyactive.net"

[[routes]]
pattern = "wk.tinyactive.net"
zone_name = "tinyactive.net"
custom_domain = true

[placement]
mode = "smart"

[[kv_namespaces]]
id = "2495644a445c4566972ef002e0845d8d"
binding = "EDGE_CACHE"

[[services]]
binding = "tinyactive.net/*"
service = "tiny"
environment = "production"
